### ISSUE TITLE
Cannot get it to work. 

### ISSUE THREAD

**Issue by mrvudo** [edlinklater/silverstripe-cloudassets-s3#4]
I have created created a bucket. The KEY and Secret are correct.
I have created cloudassets.yml

I have uploaded files but nothing is appearing in the bucket

/mysite/_config/cloudassets.yml

```
CloudAssets: 
    map: 'assets/Uploads'
    Type: S3Bucket 
    BaseURL: '' 
    Container: bucketname
    Region: location
    ApiKey: apikey
    ApiSecret: apisecret
    LocalCopy: true 
```

I have ran /dev/build/?flush=1

Am I missing anything?

**Comment by markguinn** [comment]
If you compare what you've got here to the example in the readme, you'll see that your indention is off. Configuration files are YML so indentation means something and must be consistent, ideally with spaces.

**Comment by mrvudo** [comment]
```
CloudAssets: 
  map: 
    'assets/Uploads':
      Type: S3Bucket 
      BaseURL: 'amazons3.url' 
      Container: bucket
      Region: location
      ApiKey: apikey
      ApiSecret: apisecret
      LocalCopy: true
```

This is what I have now but still nothing. Is there a way I can check if the connection is working?

Do I need the BaseURL? Do I get it from `Static Website Hosting` in the s3 bucket properties?
